
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:27798811143:android:a5bec44982037c399f30a2",
        firebase_cli_token: ENV["1//03IMOMzZr13rpCgYIARAAGAMSNwF-L9IryHtQUSmXll3X-Z1H0fyjYUTJRiE1NlgAHyveGhdR721yktvQn3GAIWkVKgdsU2t4jk8"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "mohamedyousrey321@gmail.com",
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end